version: '3.7'

services:
  electrum:
    build: .
    environment:
      - ELECTRUM_USER=electrum
      - ELECTRUM_PASSWORD=changeme
      - ELECTRUM_NETWORK=testnet
      - ELECTRUM_VERSION=4.1.5
      - ELECTRUM_CHECKSUM_SHA512=12
      - ELECTRUM_HOME=/home/electrum
    ports:
      - 127.0.0.1:7000:7000
    environment:
      ELECTRUM_USER: electrum
      ELECTRUM_PASSWORD: changeme
      ELECTRUM_NETWORK: testnet
    container_name: electrum
    image:  osminogin/docker-electrum-daemon
    volumes:
        - ../electrum:/data