version: '3.7'

services:
  electrum:
    build: .
    ports:
      - 127.0.0.1:7000:7000
    environment:
      ELECTRUM_USER: electrum
      ELECTRUM_PASSWORD: changeme
      TESTNET: False
    container_name: electrum
    image:  osminogin/docker-electrum-daemon
    volumes:
        - ../electrum:/data
